export type GearSlotsType = {
  [key: string]: { label: string; imageSrc: string }[];
};

export const gearSlots: GearSlotsType = {
  barbarian: [
    { label: 'Helm', imageSrc: '/images/icons/gear/helm.webp' },
    { label: 'Chest Armor', imageSrc: '/images/icons/gear/chest_armor.webp' },
    { label: 'Gloves', imageSrc: '/images/icons/gear/gloves.webp' },
    { label: 'Pants', imageSrc: '/images/icons/gear/pants.webp' },
    { label: 'Boots', imageSrc: '/images/icons/gear/boots.webp' },
    { label: 'Bludgeoning Weapon', imageSrc: '/images/icons/gear/bludgeoning_weapon.webp' },
    { label: 'Dual-Wield Weapon 1', imageSrc: '/images/icons/gear/dual_wield_weapon_1.webp' },
    { label: 'Amulet', imageSrc: '/images/icons/gear/amulet.webp' },
    { label: 'Ring 1', imageSrc: '/images/icons/gear/ring_1.webp' },
    { label: 'Ring 2', imageSrc: '/images/icons/gear/ring_2.webp' },
    { label: 'Slashing Weapon', imageSrc: '/images/icons/gear/slashing_weapon.webp' },
    { label: 'Dual-Wield Weapon 2', imageSrc: '/images/icons/gear/dual_wield_weapon_2.webp' },
  ],
  druid: [
    { label: 'Helm', imageSrc: '/images/icons/gear/helm.webp' },
    { label: 'Chest Armor', imageSrc: '/images/icons/gear/chest_armor.webp' },
    { label: 'Gloves', imageSrc: '/images/icons/gear/gloves.webp' },
    { label: 'Pants', imageSrc: '/images/icons/gear/pants.webp' },
    { label: 'Boots', imageSrc: '/images/icons/gear/boots.webp' },
    { label: 'Weapon', imageSrc: '/images/icons/gear/weapon.webp' },
    { label: 'Amulet', imageSrc: '/images/icons/gear/amulet.webp' },
    { label: 'Ring 1', imageSrc: '/images/icons/gear/ring_1.webp' },
    { label: 'Ring 2', imageSrc: '/images/icons/gear/ring_2.webp' },
    { label: 'Offhand', imageSrc: '/images/icons/gear/offhand.webp' },
  ],
  necromancer: [
    { label: 'Helm', imageSrc: '/images/icons/gear/helm.webp' },
    { label: 'Chest Armor', imageSrc: '/images/icons/gear/chest_armor.webp' },
    { label: 'Gloves', imageSrc: '/images/icons/gear/gloves.webp' },
    { label: 'Pants', imageSrc: '/images/icons/gear/pants.webp' },
    { label: 'Boots', imageSrc: '/images/icons/gear/boots.webp' },
    { label: 'Weapon', imageSrc: '/images/icons/gear/weapon.webp' },
    { label: 'Amulet', imageSrc: '/images/icons/gear/amulet.webp' },
    { label: 'Ring 1', imageSrc: '/images/icons/gear/ring_1.webp' },
    { label: 'Ring 2', imageSrc: '/images/icons/gear/ring_2.webp' },
    { label: 'Offhand', imageSrc: '/images/icons/gear/offhand.webp' },
  ],
  rogue: [
    { label: 'Helm', imageSrc: '/images/icons/gear/helm.webp' },
    { label: 'Chest Armor', imageSrc: '/images/icons/gear/chest_armor.webp' },
    { label: 'Gloves', imageSrc: '/images/icons/gear/gloves.webp' },
    { label: 'Pants', imageSrc: '/images/icons/gear/pants.webp' },
    { label: 'Boots', imageSrc: '/images/icons/gear/boots.webp' },
    { label: 'Ranged Weapon', imageSrc: '/images/icons/gear/ranged_weapon.webp' },
    { label: 'Dual-Wield Weapon 1', imageSrc: '/images/icons/gear/dual_wield_weapon_1.webp' },
    { label: 'Amulet', imageSrc: '/images/icons/gear/amulet.webp' },
    { label: 'Ring 1', imageSrc: '/images/icons/gear/ring_1.webp' },
    { label: 'Ring 2', imageSrc: '/images/icons/gear/ring_2.webp' },
    { label: 'Dual-Wield Weapon 2', imageSrc: '/images/icons/gear/dual_wield_weapon_2.webp' },
  ],
  sorcerer: [
    { label: 'Helm', imageSrc: '/images/icons/gear/helm.webp' },
    { label: 'Chest Armor', imageSrc: '/images/icons/gear/chest_armor.webp' },
    { label: 'Gloves', imageSrc: '/images/icons/gear/gloves.webp' },
    { label: 'Pants', imageSrc: '/images/icons/gear/pants.webp' },
    { label: 'Boots', imageSrc: '/images/icons/gear/boots.webp' },
    { label: 'Weapon', imageSrc: '/images/icons/gear/weapon.webp' },
    { label: 'Amulet', imageSrc: '/images/icons/gear/amulet.webp' },
    { label: 'Ring 1', imageSrc: '/images/icons/gear/ring_1.webp' },
    { label: 'Ring 2', imageSrc: '/images/icons/gear/ring_2.webp' },
    { label: 'Offhand', imageSrc: '/images/icons/gear/offhand.webp' },
  ],
  spiritborn: [
    { label: 'Helm', imageSrc: '/images/icons/gear/helm.webp' },
    { label: 'Chest Armor', imageSrc: '/images/icons/gear/chest_armor.webp' },
    { label: 'Gloves', imageSrc: '/images/icons/gear/gloves.webp' },
    { label: 'Pants', imageSrc: '/images/icons/gear/pants.webp' },
    { label: 'Boots', imageSrc: '/images/icons/gear/boots.webp' },
    { label: 'Weapon', imageSrc: '/images/icons/gear/weapon.webp' },
    { label: 'Amulet', imageSrc: '/images/icons/gear/amulet.webp' },
    { label: 'Ring 1', imageSrc: '/images/icons/gear/ring_1.webp' },
    { label: 'Ring 2', imageSrc: '/images/icons/gear/ring_2.webp' },
  ],
};

export const gemSlots = [
  { label: 'Weapon', imageSrc: '/images/icons/gear/gems.webp' },
  { label: 'Armor', imageSrc: '/images/icons/gear/gems.webp' },
  { label: 'Amulet', imageSrc: '/images/icons/gear/gems.webp' },
  { label: 'Ring 1', imageSrc: '/images/icons/gear/gems.webp' },
  { label: 'Ring 2', imageSrc: '/images/icons/gear/gems.webp' },
];
